### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by wiktoriatomzik** [ukwa/docker-heritrix#1]
Could you please add the running instructions (working ones) to the readme file?

**Comment by anjackson** [comment]
Sorry, we've moved away from the approach here and the current UKWA production Heritrix container is at: https://github.com/ukwa/ukwa-heritrix 

That version can be started using the supplied `docker-compose.yml` file, but may be too heavily tuned to our needs to be generally useful. Do let us know how you get on.
